apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: app-postgres
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: app-postgres
        app: app
    spec:
      containers:
      - name: postgres
        image: postgres:12.4
        imagePullPolicy: IfNotPresent
        envFrom:
          - configMapRef:
              name: postgres-config
        ports:
        - containerPort: 5432
          name: postgres
        volumeMounts:
        - mountPath: /var/lib/postgresql/data
          name: postgres-persistent-storage
      imagePullSecrets:
        - name: nabucco-docker-registry-secret
      restartPolicy: Always
      volumes:
      - name: postgres-persistent-storage
        persistentVolumeClaim:
          claimName: postgres-pvc
