apiVersion: apps/v1
kind: Deployment
metadata:
  name: shopapp-user-service
  labels:
    app: shopapp-user-service
spec:
  replicas: 1
  template:
    metadata:
      name: shopapp-user-service
      labels:
        app: shopapp-user-service
    spec:
      containers:
        - name: shopapp-user-service
          image: shopapp-user-service
          imagePullPolicy: IfNotPresent
      restartPolicy: Always
  selector:
    matchLabels:
      app: shopapp-user-service
---
apiVersion: v1
kind: Service
metadata:
  name: shopapp-user-service
spec:
  selector:
    app: shopapp-user-service
  ports:
    - port: 8080
  type: LoadBalancer