##  
alertmanager:
  enabled: true

  ingress:
    enabled: true
    annotations:
      kubernetes.io/ingress.class: nginx
    hosts: 
      - alertmanager.kubernetes.local

  persistentVolume:
    enabled: true
    accessModes:
      - ReadWriteOnce
    size: 2Gi
    storageClass: "standard"

##  
kubeStateMetrics:
  enabled: true

##  
nodeExporter:
  enabled: true

##  
server:
  enabled: true

  ingress:
    enabled: true
    annotations:
      kubernetes.io/ingress.class: nginx
    hosts:
      - prometheus.kubernetes.local

  persistentVolume:
    enabled: true
    accessModes:
      - ReadWriteOnce
    size: 8Gi
    storageClass: "standard"
    
##  
pushgateway:
  enabled: true

  ingress:
    enabled: true
    annotations:
      kubernetes.io/ingress.class: nginx
    hosts: 
      - pushgateway.kubernetes.local

  persistentVolume:
    enabled: true
    accessModes:
      - ReadWriteOnce
    size: 2Gi
    storageClass: "standard"

