kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
networking:
  disableDefaultCNI: true
  podSubnet: 172.10.0.0/16
  serviceSubnet: 172.20.0.0/16
nodes:
- role: control-plane
  image: kindest/node:v1.19.0
  extraPortMappings:
  - containerPort: 80
    hostPort: 80
    protocol: TCP
  - containerPort: 433
    hostPort: 433
    protocol: TCP
- role: worker
  image: kindest/node:v1.19.0
- role: worker
  image: kindest/node:v1.19.0
