apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: kubernetes-certificates
  namespace: kube-system
spec:
  secretName: letsencrypt-secret
  duration: 2160h # 90d
  renewBefore: 360h # 15d
  issuerRef:
    name: letsencrypt
    kind: ClusterIssuer
  dnsNames:
  - registry.kubernetes.local
