apiVersion: v1
kind: Service
metadata: 
  name: postgres-service
  namespace: default
  labels: 
    name: postgres
    app: app
spec: 
  selector:
    name: app-postgres
  ports:
    - port: 5432
      targetPort: 5432
      protocol: TCP
  type: LoadBalancer
