# -*- mode: ruby -*-
# vi: set ft=ruby :

ENV['VAGRANT_NO_PARALLEL'] = 'yes'

WorkerNodeCount = 2

Vagrant.configure(2) do |config|


  # Kubernetes Master Server
  config.vm.define "k8s-master" do |k8smaster|
    k8smaster.vm.box = "ubuntu/xenial64"
    k8smaster.vm.hostname = "k8s-master.xvitcoder.com"
    k8smaster.vm.network "private_network", ip: "172.42.42.100"
    k8smaster.vm.provider "virtualbox" do |v|
      v.name = "k8s-master"
      v.memory = 2048
      v.cpus = 2
      # Prevent VirtualBox from interfering with host audio stack
      v.customize ["modifyvm", :id, "--audio", "none"]
      # Prevent vagrant to write console.log file
      v.customize ["modifyvm", :id, "--uartmode1", "disconnected"]
    end
    k8smaster.vm.provision "shell", path: "bootstrap.sh"
    k8smaster.vm.provision "shell", path: "bootstrap-k8s-master.sh"
  end


  # Kubernetes Worker Nodes
  (1..WorkerNodeCount).each do |i|
    config.vm.define "k8s-worker#{i}" do |workernode|
      workernode.vm.box = "ubuntu/xenial64"
      workernode.vm.hostname = "k8s-worker#{i}.xvitcoder.com"
      workernode.vm.network "private_network", ip: "172.42.42.10#{i}"
      workernode.vm.provider "virtualbox" do |v|
        v.name = "kworker#{i}"
        v.memory = 1024
        v.cpus = 2
        # Prevent VirtualBox from interfering with host audio stack
        v.customize ["modifyvm", :id, "--audio", "none"]
        # Prevent vagrant to write console.log file
        v.customize ["modifyvm", :id, "--uartmode1", "disconnected"]
      end
      workernode.vm.provision "shell", path: "bootstrap.sh"
      workernode.vm.provision "shell", path: "bootstrap-k8s-worker.sh"
    end
  end


  # NFS Server
  config.vm.define "k8s-nfs" do |k8snfs|
    k8snfs.vm.box = "ubuntu/xenial64"
    k8snfs.vm.hostname = "k8s-nfs.xvitcoder.com"
    k8snfs.vm.network "private_network", ip: "172.42.42.10"
    k8snfs.vm.provider "virtualbox" do |v|
      v.name = "k8s-nfs"
      v.memory = 1024
      v.cpus = 1
      # Prevent VirtualBox from interfering with host audio stack
      v.customize ["modifyvm", :id, "--audio", "none"]
      # Prevent vagrant to write console.log file
      v.customize ["modifyvm", :id, "--uartmode1", "disconnected"]
    end
    k8snfs.vm.provision "shell", path: "bootstrap-k8s-nfs.sh"
  end

end
